"""Check SONICS real-fake mapping and verify downloaded samples."""

import pandas as pd

fake = pd.read_csv("data/raw/sonics/metadata/fake_songs.csv")
print("=== FAKE SONGS ===")
print("Columns:", list(fake.columns))
print("Shape:", fake.shape)
print()

our_fakes = [
    "fake_50960_suno_0",
    "fake_50960_suno_1",
    "fake_50961_suno_0",
    "fake_50961_suno_1",
    "fake_50962_suno_0",
]
for fn in our_fakes:
    row = fake[fake["filename"] == fn]
    if not row.empty:
        r = row.iloc[0]
        print(f"  {fn}:")
        print(
            f"    algorithm={r['algorithm']}, style={r['style']}, "
            f"genre={r.get('genre','?')}, label={r['label']}, split={r['split']}"
        )
        if "lyrics" in fake.columns:
            print(f"    lyrics preview: {str(r['lyrics'])[:80]}...")
    else:
        print(f"  {fn}: NOT FOUND in CSV")

print()
print("=== REAL SONGS ===")
real = pd.read_csv("data/raw/sonics/metadata/real_songs.csv")
print("Columns:", list(real.columns))
print("Shape:", real.shape)
print()

our_reals = ["QYh6mYIJG2Y", "FAucVNRx_mU", "gG_dA32oH44", "vJwKKKd2ZYE", "m8QQR-wQA0I"]
for yt_id in our_reals:
    row = real[real["youtube_id"] == yt_id]
    if not row.empty:
        r = row.iloc[0]
        print(
            f"  {yt_id}: title=\"{r.get('title','?')}\", "
            f"artist=\"{r.get('artist','?')}\", split={r.get('split','?')}, "
            f"label={r.get('label','?')}"
        )
    else:
        print(f"  {yt_id}: NOT FOUND in real_songs.csv")

print()
print("=== PAIRING CHECK ===")
common = set(fake.columns) & set(real.columns)
print("Common columns:", common)

# Check if fake songs reference real songs in any way
if "source" in fake.columns:
    print()
    print("Fake 'source' values:", fake["source"].unique()[:10])

if "id" in fake.columns:
    print()
    print("Fake 'id' sample:", fake["id"].head())

# SONICS is NOT a paired dataset - fakes are independently generated
# Real = scraped from YouTube, Fake = generated by AI models (Suno, Udio, etc.)
# No 1-to-1 mapping exists. We just need samples from each class.
print()
print("=== CONCLUSION ===")
print("SONICS is a classification dataset (real vs fake), NOT a paired dataset.")
print("Fakes are independently generated by AI models, not derived from specific reals.")
print("For ID estimation we need representative samples from each class - no pairing needed.")
